import { useContext } from "react";

import MainLayout from "../layouts/MainLayout";
import AgentCard from "../components/AgentCard";
import VotingPanel from "../components/VotingPanel";
import DebatePanel from "../components/DebatePanel";
import FinalVerdictCard from "../components/FinalVerdictCard";

import { VerdictContext } from "../context/VerdictContext";

const Reports = () => {
  const { result } = useContext(VerdictContext);

  const startupIdeaText =
    typeof result?.startupIdea === "object"
      ? result?.startupIdea?.idea
      : result?.startupIdea;

  return (
    <MainLayout>
      <div className="space-y-10">
        {/* Header */}
        <div>
          <h1 className="text-4xl font-bold text-white">
            Reports
          </h1>

          <p className="mt-2 text-zinc-400">
            Detailed AI startup analysis generated by VerdictOS.
          </p>
        </div>

        {/* Empty State */}
        {!result ? (
          <div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-10 text-center">
            <h2 className="text-2xl font-semibold text-white">
              No Report Available
            </h2>

            <p className="mt-3 text-zinc-400">
              Analyze a startup idea from the Dashboard
              to generate reports.
            </p>
          </div>
        ) : (
          <>
            {/* Startup Idea */}
            <div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-6">
              <h2 className="mb-3 text-xl font-bold text-white">
                Startup Idea
              </h2>

              <p className="leading-relaxed text-zinc-300">
                {startupIdeaText || "N/A"}
              </p>
            </div>

            {/* Agent Reports */}
            <div>
              <h2 className="mb-5 text-2xl font-bold text-white">
                🧠 Agent Analysis
              </h2>

              <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">
                {(result?.reports || []).map(
                  (report, index) => (
                    <AgentCard
                      key={report?.agent || index}
                      report={report}
                    />
                  )
                )}
              </div>
            </div>

            {/* Voting */}
            {result?.voting && (
              <div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-6">
                <h2 className="mb-4 text-xl font-bold text-white">
                  🗳 Voting Results
                </h2>

                <VotingPanel
                  voting={result.voting}
                />
              </div>
            )}

            {/* Debate */}
            {result?.debate && (
              <div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-6">
                <h2 className="mb-4 text-xl font-bold text-white">
                  🧠 AI Boardroom Debate
                </h2>

                <DebatePanel
                  debate={result.debate}
                />
              </div>
            )}

            {/* Final Verdict */}
            {result?.finalVerdict && (
              <FinalVerdictCard
                verdict={result.finalVerdict}
              />
            )}
          </>
        )}
      </div>
    </MainLayout>
  );
};

export default Reports;